[parity]
mode = "last"
mode_timeout = 300
mode_alarm = 3600
auto_update = "none"
auto_update_delay = 200
auto_update_check_frequency = 50
release_track = "current"
public_node = false
no_download = false
no_consensus = false
no_persistent_txqueue = false

chain = "seekchain"
base_path = "$HOME/.seekchain"
db_path = "$HOME/.seekchain/chains"
keys_path = "$HOME/.seekchain/keys"
identity = ""
light = false
no_hardcoded_sync = false

[network]
port = 30303
min_peers = 25
max_peers = 50
nat = "any"
bootnodes = ["enode://3334979463ef5ca263562839acde40c1a8e916aa704e13106cf0c778457b3f9f9a149c5f642ced644d26bd30c855da437abf520ebdba12bf9443ab553dfe268e@13.251.6.203:30303","enode://dfdfb7696bc492341c23a0a5bf73c73ed140143e7673f18c7888fd64e4ecc818c243cf4ce9e9c13aa65fb08d0ab4906ed3a8e277d1c3e2839991b46527526fb5@182.61.139.140:30303","enode://5cade41b0c78a98f76807eba715c7650b5fc51ab6187f0cbfef0b5ed13393a13ed61efa4342f409ee4007b2fe717cc9a946ba191d6fd7d5af617483b68b373ff@104.236.240.227:30304","enode://72bec7b8ed04cd3383fe9bc15f952cbaf24398ed507553d9bb13bb53730eece990bd833f026fc1d74e97a2c6a45b5aa894954e6d681e1368b8d8e2cc5bb4098a@182.61.110.193:30303","enode://b585f731f52cb769cc171f91d27e6a443de036b8e3940a70bf3016e9e92778952fe013be751adb533bff3f7d41f644ea2d924492ba11bd3ffe91768b780595e9@134.209.104.209:30304"]
discovery = true
warp = true
allow_ips = "all"
snapshot_peers = 0
max_pending_peers = 64
no_serve_light = false

[rpc]
disable = false
port = 8545
interface = "local"
cors = ["*"]
apis = ["web3", "eth", "net", "parity", "parity_set", "traces", "rpc", "secretstore"]
hosts = ["*"]
allow_missing_blocks = false

[websockets]
disable = false
port = 8546
interface = "local"
origins = ["*"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["*"]

[ipc]
disable = false
#path = "/Users/admin/parity-eth/jsonrpc.ipc"
apis = ["web3", "eth", "net", "parity", "parity_accounts", "personal", "traces", "rpc", "secretstore"]

[ipfs]
enable = false
port = 5001
interface = "local"
cors = ["null"]
hosts = ["none"]

[account]
#unlock = ["0x54e6f8af5fc2f585b269f5992a66cf6b2cfaa6e6"]
#password = ["/root/seekchain/password.txt"]

[mining]
#author = "0x54e6f8af5fc2f585b269f5992a66cf6b2cfaa6e6"
#engine_signer = "0x54e6f8af5fc2f585b269f5992a66cf6b2cfaa6e6"
#force_sealing = true
#reseal_on_txs = "all"
#reseal_min_period = 4000
#reseal_max_period = 60000
#work_queue_size = 20
#relay_set = "cheap"
#min_gas_price = 0
#usd_per_tx = "0.0001"
#usd_per_eth = "auto"
#price_update_period = "hourly"
#gas_floor_target = "8000000"
#gas_cap = "10000000"
#tx_queue_size = 8192
#tx_queue_locals = ["0x54e6f8af5fc2f585b269f5992a66cf6b2cfaa6e6"]
#tx_gas_limit = "10000000"
#tx_time_limit = 100 #ms
#tx_queue_no_unfamiliar_locals = false
#tx_queue_no_early_reject = false
#extra_data = "Parity"
#remove_solved = false
#notify_work = ["http://localhost:3001"]
#refuse_service_transactions = false

[footprint]
tracing = "auto"
pruning = "auto"
pruning_history = 64
pruning_memory = 500
cache_size_db = 64
cache_size_blocks = 8
cache_size_queue = 50
cache_size_state = 25
cache_size = 128 # Overrides above caches with total size
db_compaction = "ssd"
fat_db = "auto"
scale_verifiers = true
num_verifiers = 6

[light]
on_demand_response_time_window = 2
on_demand_request_backoff_start = 9
on_demand_request_backoff_max = 15
on_demand_request_backoff_rounds_max = 100
on_demand_request_consecutive_failures = 1

[snapshots]
disable_periodic = false

[whisper]
enabled = false
pool_size = 20

[misc] 
logging = "error"
log_file = "./parity.log"
color = true
